STYLE = {
    "random_seed": 42,
    "colors": {
        "paper": "#F5F7FB",
        "paper_alt": "#EEF2F7",
        "dark_brown": "#111827",
        "medium_brown": "#334155",
        "light_wood": "#E2E8F0",
        "sand": "#F8FAFC",
        "text": "#111827",
        "charcoal_border": "#64748B",
        "header_text": "#FFFFFF",
        "creation": "#EAF4FF",
        "materials": "#EFFBF3",
        "upgrade_1": "#FFF6E6",
        "upgrade_2": "#F2F0FF",
        "upgrade_3": "#F0FBFF",
        "quantity_bg": "#1F2937",
        "legend_use": "#2563EB",
        "legend_attack": "#DC2626",
        "legend_movement": "#0891B2",
        "legend_draw": "#475569",
        "legend_defense": "#16A34A",
        "legend_special": "#9333EA",
        "legend_range": "#EA580C",
        "legend_accessory": "#0F766E",
        "materials_text": "#14532D",
        "upgrade_1_text": "#7C2D12",
        "upgrade_2_text": "#312E81",
        "upgrade_3_text": "#0E7490",
        "creation_alt": "#DCEEFF",
        "quantity_alt": "#334155",
    },
    "paper": {
        "base_color": "#F5F7FB",
        "external_texture_enabled": False,
        "external_texture_opacity": 0.0,
        "width_px": 3508,
        "height_px": 2480,
        "noise": 1,
        "wash_strength": 3,
        "wash_scale": 18,
        "fibers": False,
        "fiber_count": 0,
        "fiber_color": "#CBD5E1",
        "speckles": False,
        "speckle_count": 0,
        "speckle_color": "#CBD5E1",
        "stains": False,
        "stain_count": 0,
        "stain_color": "#CBD5E1",
        "edge_aging": False,
        "edge_darkening_strength": 0,
        "edge_width_ratio": 0.0,
        "modern_graphics": True,
        "grid_color": "#D8DEE8",
        "grid_opacity": 115,
        "accent_blue": "#38BDF8",
        "accent_orange": "#FB923C",
        "accent_green": "#34D399",
        "accent_purple": "#A78BFA",
    },
    "watercolor": {
        "enabled": False,
        "external_assets_enabled": False,
        "external_asset_opacity": 0,
        "external_pattern_opacity": 0,
        "external_pattern_height": 610,
        "opacity": 42,
        "corner_opacity": 100,
        "central_opacity": 44,
        "blur_radius": 1.4,
        "twig_color": "#6B5637",
        "leaf_color": "#6D7442",
        "berry_color": "#8C3F32",
        "stone_color": "#6E6A5E",
        "margin_marks": 10,
    },
    "page": {
        "size": "A4",
        "orientation": "landscape",
        "margin_mm": 4.0,
        "background_color": "#F5F7FB",
        "texture_opacity": 0.0,
    },
    "fonts": {
        "regular": "Helvetica",
        "bold": "Helvetica-Bold",
        "title": "Helvetica-Bold",
        "hand": "Helvetica-Bold",
        "symbols": "MenuSymbols",
        "fallback_regular": "Helvetica",
        "fallback_bold": "Helvetica-Bold",
        "fallback_title": "Helvetica-Bold",
        "fallback_hand": "Helvetica-Bold",
    },
    "header": {
        "font_size": 9.8,
        "leading": 10.4,
        "padding": 4.2,
        "background": "#111827",
        "text_color": "#FFFFFF",
        "align": "CENTER",
    },
    "table": {
        "inner_grid_width": 0.55,
        "outer_grid_width": 1.25,
        "border_color": "#64748B",
        "repeat_header": True,
        "fill_height_ratio": 0.965,
    },
    "cell": {
        "font_size": 7.9,
        "leading": 8.8,
        "padding_left": 4.2,
        "padding_right": 4.2,
        "padding_top": 4.2,
        "padding_bottom": 4.2,
        "min_row_height": None,
        "text_color": "#111827",
        "align": "LEFT",
        "valign": "TOP",
    },
    "creation": {
        "font_size": 7.9,
        "leading": 8.8,
        "name_font_size": 10.4,
        "name_leading": 11.2,
        "detail_font_size": 7.5,
        "background": "#EAF4FF",
        "text_color": "#111827",
        "bold": True,
        "align": "LEFT",
    },
    "quantity": {
        "font_size": 11.0,
        "leading": 11.4,
        "background": "#1F2937",
        "text_color": "#FFFFFF",
        "bold": True,
        "align": "CENTER",
    },
    "materials": {
        "background": "#EFFBF3",
        "align": "LEFT",
    },
    "upgrade_1": {
        "background": "#FFF6E6",
        "align": "LEFT",
    },
    "upgrade_2": {
        "background": "#F2F0FF",
        "align": "LEFT",
    },
    "upgrade_3": {
        "background": "#F0FBFF",
        "align": "LEFT",
    },
    "columns": {
        "relative_widths": [1.25, 0.22, 1.38, 0.16, 1.52, 0.22, 1.45, 0.22, 1.52, 0.22],
    },
    "icons": {
        "size": 10,
        "gap": 3,
    },
    "watermark": {
        "corner_inset": 0.35,
    },
    "legend_icons": {
        "size": 17,
        "symbol_width": 28,
        "use": "use.png",
        "attack": "attack.png",
        "movement": "movement.png",
        "draw": "draw.png",
        "defense": "defense.png",
        "special": "special.png",
        "range": "range.png",
        "accessory": "accessory.png",
    },
    "footer": {
        "background": "#FFFFFF",
        "border_color": "#64748B",
        "border_width": 1.0,
        "font": "Helvetica",
        "font_size": 8.2,
        "leading": 9.2,
        "title_font": "Helvetica-Bold",
        "title_size": 10.8,
        "title_leading": 11.4,
        "text_color": "#111827",
        "padding": 4.8,
        "spacing": 4.6,
        "item_gap": 5,
        "columns": 3,
        "signature_enabled": False,
        "signature_text": "",
    },
    "resources": {
        "separator": "&nbsp;&nbsp;&nbsp;",
        "quantity_marker": "x",
    },
    "semantic_highlights": {
        "enabled": True,
        "bold": True,
        "highlight_inline_terms": False,
        "label_background": "#F2E4BD",
        "label_padding": 1,
        "symbol_color": "#111827",
        "label_terms": [
            "Attacco",
            "Movimento",
            "Difesa",
            "Estrazione",
            "Accessorio",
            "Accendi",
            "Spegni",
            "Termina",
            "Reazione",
        ],
        "rules": [
            {
                "name": "danni",
                "color": "#DC2626",
                "terms": ["danno", "danni", "attacco", "attacca", "ferisci"],
            },
            {
                "name": "bacche",
                "color": "#7C3AED",
                "terms": ["bacca", "bacche", "succo di bacca"],
            },
            {
                "name": "pietra",
                "color": "#475569",
                "terms": ["pietra", "pietre", "lastra"],
            },
            {
                "name": "legno",
                "color": "#92400E",
                "terms": ["ramo", "rami", "legno", "bastone"],
            },
            {
                "name": "pelle",
                "color": "#B45309",
                "terms": ["pelle"],
            },
            {
                "name": "corda",
                "color": "#D97706",
                "terms": ["corda", "corde", "laccio", "lacci"],
            },
            {
                "name": "movimento",
                "color": "#0891B2",
                "terms": ["movimento", "muovi", "salta", "esagoni", "linea retta", "linee rette", "raggio", "raggi"],
            },
            {
                "name": "difesa",
                "color": "#16A34A",
                "terms": ["difesa", "difendi", "schiva", "evita", "para"],
            },
            {
                "name": "azione",
                "color": "#7C3AED",
                "terms": ["azione", "azioni", "estrazione", "estrai"],
            },
            {
                "name": "gittata",
                "color": "#EA580C",
                "terms": ["gittata"],
            },
            {
                "name": "accessorio",
                "color": "#7B5531",
                "terms": ["accessorio", "accessori"],
            },
            {
                "name": "speciale",
                "color": "#9A6B1F",
                "terms": ["speciale", "accendi", "spegni", "brucia"],
            },
        ],
    },
    "text": {
        "empty_cell": "—",
        "strip_unreadable_notes": True,
    },
}
